<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('municipalities')->insert([
            ['nombre_municipio' => 'ACAMBAY DE RUIZ CASTAÑEDA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ACOLMAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ACULCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ALMOLOYA DE ALQUISIRAS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ALMOLOYA DE JUÁREZ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ALMOLOYA DEL RÍO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'AMANALCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'AMATEPEC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'AMECAMECA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'APAXCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ATENCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ATIZAPÁN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ATIZAPÁN DE ZARAGOZA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ATLACOMULCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ATLAUTLA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'AXAPUSCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'AYAPANGO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'CALIMAYA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'CAPULHUAC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'COACALCO DE BERRIOZÁBAL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'COATEPEC HARINAS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'COCOTITLÁN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'COYOTEPEC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'CUAUTITLÁN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'CUAUTITLÁN IZCALLI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'CHALCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'CHAPA DE MOTA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'CHAPULTEPEC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'CHIAUTLA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'CHICOLOAPAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'CHICONCUAC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'CHIMALHUACÁN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'DONATO GUERRA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ECATEPEC DE MORELOS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ECATZINGO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'HUEHUETOCA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'HUEYPOXTLA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'HUIXQUILUCAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ISIDRO FABELA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'IXTAPALUCA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'IXTAPAN DE LA SAL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'IXTAPAN DEL ORO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'IXTLAHUACA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'XALATLACO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'JALTENCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'JILOTEPEC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'JILOTZINGO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'JIQUIPILCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'JOCOTITLÁN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'JOQUICINGO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'JUCHITEPEC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'LERMA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'MALINALCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'MELCHOR OCAMPO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'METEPEC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'MEXICALTZINGO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'MORELOS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'NAUCALPAN DE JUÁREZ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'NEXTLALPAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'NEZAHUALCÓYOTL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'NICOLÁS ROMERO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'NOPALTEPEC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'OCOYOACAC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'OCUILAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'EL ORO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'OTUMBA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'OTZOLOAPAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'OTZOLOTEPEC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'OZUMBA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'PAPALOTLA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'LA PAZ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'POLOTITLÁN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'RAYÓN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'SAN ANTONIO LA ISLA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'SAN FELIPE DEL PROGRESO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'SAN MARTÍN DE LAS PIRÁMIDES', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'SAN MATEO ATENCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'SAN SIMÓN DE GUERRERO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'SANTO TOMÁS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'SOYANIQUILPAN DE JUÁREZ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'SULTEPEC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TECÁMAC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEJUPILCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEMAMATLA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEMASCALAPA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEMASCALCINGO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEMASCALTEPEC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEMOAYA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TENANCINGO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TENANGO DEL AIRE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TENANGO DEL VALLE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEOLOYUCAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEOTIHUACÁN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEPETLAOXTOC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEPETLIXPA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEPOTZOTLÁN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEQUIXQUIAC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEXCALTITLÁN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEXCALYACAC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEXCOCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TEZOYUCA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TIANGUISTENCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TIMILPAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TLALMANALCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TLALNEPANTLA DE BAZ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TLATLAYA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TOLUCA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TONATICO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TULTEPEC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TULTITLÁN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'VALLE DE BRAVO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'VILLA DE ALLENDE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'VILLA DEL CARBÓN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'VILLA GUERRERO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'VILLA VICTORIA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'XONACATLÁN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ZACAZONAPAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ZACUALPAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ZINACANTEPEC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ZUMPAHUACÁN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'ZUMPANGO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'VALLE DE CHALCO SOLIDARIDAD', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'LUVIANOS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'SAN JOSÉ DEL RINCÓN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => 'TONANITLA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre_municipio' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

        ]);
    }
}
